import mobileNav from './modules/mobile-nav.js';
import cursor from './modules/cursor.js';
import swiperComments from './modules/swiper-comments.js';
import swiperTeam from './modules/swiper-team.js';
import swiperWeProud from './modules/swiper-we-proud.js';
import aboutus from './modules/AboutUs.js';
import services from './modules/services.js';
import swiperCases from './modules/swiper-Cases.js';
import cases from './modules/Cases.js';
import filterCases from './modules/filterCases.js';
import btnUp from './modules/btn-up.js';
import bitrixPage from './modules/bitrix-page.js';
import benefits from './modules/benefits.js';

// btnUp();
benefits();
filterCases();
bitrixPage();
cases();
swiperCases();
swiperWeProud();
swiperTeam();
swiperComments();
mobileNav();
cursor();
aboutus();
services();